// <auto-generated />
using System;
using SURV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SURV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190528092821_Initial03")]
    partial class Initial03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SURV.Models.DB.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Body");

                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SURV.Models.DB.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DateTill")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<bool>("NonResident")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SURV.Models.DB.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SURV.Models.DB.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<string>("Currency");

                    b.Property<int?>("GradeId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<double>("Sum");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GradeId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("SURV.Models.DB.Errormessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Errormessages");
                });

            modelBuilder.Entity("SURV.Models.DB.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SURV.Models.DB.Hrmonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("DateTime");

                    b.Property<int?>("ApprovepersonId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ApprovepersonId");

                    b.ToTable("Hrmonths");
                });

            modelBuilder.Entity("SURV.Models.DB.Hryear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("DateTime");

                    b.Property<int?>("ApprovepersonId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ApprovepersonId");

                    b.ToTable("Hryears");
                });

            modelBuilder.Entity("SURV.Models.DB.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Body");

                    b.Property<bool>("Completed")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int?>("PersonId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SURV.Models.DB.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DateTill")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<string>("FullName")
                        .HasMaxLength(255);

                    b.Property<int?>("GradeId");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ManagerId");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("TabelNumber")
                        .HasMaxLength(255);

                    b.Property<int?>("UnitId");

                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<int>("WorkType");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("UnitId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SURV.Models.DB.PersonCompany", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("CompanyId");

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.HasKey("PersonId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("PersonCompanies");
                });

            modelBuilder.Entity("SURV.Models.DB.PersonRole", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("RoleId");

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.HasKey("PersonId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PersonRoles");
                });

            modelBuilder.Entity("SURV.Models.DB.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("Block")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ClientId");

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<int?>("DeputyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ManagerId");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("ViewerId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeputyId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ViewerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SURV.Models.DB.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SURV.Models.DB.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Comment");

                    b.Property<int?>("CompanyId")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int?>("ServicetypeId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("UnitId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ServicetypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("SURV.Models.DB.Serviceline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ClientId")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int?>("ProjectId")
                        .IsRequired();

                    b.Property<string>("Result")
                        .IsRequired();

                    b.Property<int?>("ServiceId")
                        .IsRequired();

                    b.Property<int?>("TabelId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TabelId");

                    b.ToTable("Servicelines");
                });

            modelBuilder.Entity("SURV.Models.DB.Servicetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Servicetypes");
                });

            modelBuilder.Entity("SURV.Models.DB.Tabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("Approve")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ApproverId");

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("Fill")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime?>("FillDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int>("Month");

                    b.Property<int?>("PersonId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Tabels");
                });

            modelBuilder.Entity("SURV.Models.DB.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ManagerId");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SURV.Models.DB.Usercalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("DateTill")
                        .HasColumnType("DATE");

                    b.Property<int>("DayType");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int?>("PersonId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PersonId");

                    b.ToTable("Usercalendars");
                });

            modelBuilder.Entity("SURV.Models.DB.Workday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<int>("DayType");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("SURV.Models.DB.Wsshour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("CreatedbyId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<int>("Hours");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("ModifiedbyId");

                    b.Property<int>("ServicelineId");

                    b.HasKey("Id");

                    b.HasIndex("ServicelineId");

                    b.ToTable("Wsshours");
                });

            modelBuilder.Entity("SURV.Models.DB.Client", b =>
                {
                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("SURV.Models.DB.Cost", b =>
                {
                    b.HasOne("SURV.Models.DB.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("SURV.Models.DB.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");
                });

            modelBuilder.Entity("SURV.Models.DB.Hrmonth", b =>
                {
                    b.HasOne("SURV.Models.DB.Person", "Approveperson")
                        .WithMany()
                        .HasForeignKey("ApprovepersonId");
                });

            modelBuilder.Entity("SURV.Models.DB.Hryear", b =>
                {
                    b.HasOne("SURV.Models.DB.Person", "Approveperson")
                        .WithMany()
                        .HasForeignKey("ApprovepersonId");
                });

            modelBuilder.Entity("SURV.Models.DB.Message", b =>
                {
                    b.HasOne("SURV.Models.DB.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SURV.Models.DB.Person", b =>
                {
                    b.HasOne("SURV.Models.DB.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("SURV.Models.DB.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("SURV.Models.DB.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("SURV.Models.DB.PersonCompany", b =>
                {
                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany("PersonCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Person", "Person")
                        .WithMany("PersonCompanies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SURV.Models.DB.PersonRole", b =>
                {
                    b.HasOne("SURV.Models.DB.Person", "Person")
                        .WithMany("PersonRoles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Role", "Role")
                        .WithMany("PersonRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SURV.Models.DB.Project", b =>
                {
                    b.HasOne("SURV.Models.DB.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SURV.Models.DB.Person", "Deputy")
                        .WithMany()
                        .HasForeignKey("DeputyId");

                    b.HasOne("SURV.Models.DB.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("SURV.Models.DB.Person", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId");
                });

            modelBuilder.Entity("SURV.Models.DB.Service", b =>
                {
                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Servicetype", "Servicetype")
                        .WithMany()
                        .HasForeignKey("ServicetypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SURV.Models.DB.Serviceline", b =>
                {
                    b.HasOne("SURV.Models.DB.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SURV.Models.DB.Tabel", "Tabel")
                        .WithMany("Services")
                        .HasForeignKey("TabelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SURV.Models.DB.Tabel", b =>
                {
                    b.HasOne("SURV.Models.DB.Person", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SURV.Models.DB.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("SURV.Models.DB.Unit", b =>
                {
                    b.HasOne("SURV.Models.DB.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SURV.Models.DB.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("SURV.Models.DB.Usercalendar", b =>
                {
                    b.HasOne("SURV.Models.DB.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("SURV.Models.DB.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("SURV.Models.DB.Wsshour", b =>
                {
                    b.HasOne("SURV.Models.DB.Serviceline", "Serviceline")
                        .WithMany("Hours")
                        .HasForeignKey("ServicelineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
